# Generated by Django 4.0.3 on 2024-06-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_courses_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='backward',
            field=models.TextField(default='no backward!', verbose_name='backward'),
        ),
        migrations.AddField(
            model_name='selection',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterModelTable(
            name='selection',
            table='Selection',
        ),
    ]
