# Generated by Django 4.0.3 on 2024-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courses_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.AddField(
            model_name='courses',
            name='file',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='guide',
            field=models.TextField(default='no guide!', verbose_name='description'),
        ),
    ]
