# Generated by Django 4.0.3 on 2024-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_courses_description_courses_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
